version: '3'
services:
  app:
    container_name: ask-suite-api
    image: ask-suite-api
    build: .
    command: npm run start
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - BASE_URL=https://pratagy.letsbook.com.br/reserva/selecao-de-quartos
      - LIMIT_MONTHS_AHEAD=19
